# Generated by Django 4.2.14 on 2024-07-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_version_github_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='api_response',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
