# Generated by Django 4.2.14 on 2024-07-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MdPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownfile',
            name='file_path',
            field=models.FileField(upload_to='markdown_files/'),
        ),
    ]
